### ISSUE TITLE
Забележки по ГИТ процеса

### ISSUE THREAD

**Issue by yavorp** [sharkoo0/WebTEX#12]
Супер е, че използвате една и съща конвенция за именоване на бранчовете. Но бих ви препоръчал да използвате по-описателни имена за бранчовете, в които да си личи какво правите. Пример за подобна конвенция може да е следната `feature/add-login-page-<your_name>`. Друго, което не е добре да се прави е да мърджвате бранчове към `development` без да са резолвнати всички коментари и без да имате одобрението на друг член от екипа. Това да изисквате одобрение от някой друг член от екипа ви помага с това, че някой ще прегледа кода, ще знае какво се случва и евентуално ще намери грешки, които не са били забелязани на първо четене.

**Comment by adikrasimirowa** [comment]
Благодарим за обратната връзка :smile:  За следващите етапи ще ползваме предложената от вас конвенция :smiley:
