### ISSUE TITLE
Разпределение на стилизацията по файлове

### ISSUE THREAD

**Issue by yavorp** [sharkoo0/WebTEX#14]
Имате глобална стилизация, това е добре, но е добре тя да се използва за общи елементи или за изнасяне на цветове, защото след като се увеличат екраните стиловете ви ще станат доста объркващи. В един момент може да се случи така, че да промените нещо за 1 файл, а то да има отражение навсякъде. Съветът ми да създадате отделен css файл за всеки ваш екран и там да се правят къстъм стилизациите за отделните HTML файлове. Друго за стилизацията, не е много добре да се използват id-та като селектор за стил, това ще го решите като използвате отделен CSS файл за HTML файл. **Table не се използва за стилизация** може да използвате `grid` и `flex`. За повече информация относно тези стратегии за стилизация може да намерите тук: https://css-tricks.com/snippets/css/a-guide-to-flexbox/ https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by adikrasimirowa** [comment]
А става ли отделен css за даден компонент? T.e в две страници имаме компонента dashboard, вместо за всяка страница(екран) да пишем по 2 пъти един и същи css за дадения компонент, да включваме само сss му (dashboard.css, footer.css и тн) . Подобно е и с навигацията - тя НЕ присъства само при автентикацията.

**Comment by yavorp** [comment]
Това, което предлагаш е добра идея. Това ще е приложимо, когато преминете към уеб компоненти. За сега предлагам следната схема: Имате общ файл със стилове (там може да си сложите стиловете за отделни компоненти). После си създавате отделни файлове за различните страници като целта на отделните файлове е да презаписвате стилове или да добавяте нови стилове за неща, които ще се използват само в дадената страница.

**Comment by adikrasimirowa** [comment]
Ако правилно съм разбрала -  правим си например аuth.css (за регистрацията и вход) и там си слагаме само css  уникален за дадената страница. 
И друг въпрос - как е по-добре, да `@import "main.css" `във всеки един от тези нови  css-a или в html-a(в head), първо слагаме  main.css и след това съответния css?

**Comment by yavorp** [comment]
Правилно си разбрала. Както прецените. Аз нямам никакви претенции. Важното е да е консистентно
