### ISSUE TITLE
Проблеми с използваната стилизация

### ISSUE THREAD

**Issue by yavorp** [sharkoo0/WebTEX#15]
Често допускана грешка е да използвате тагът `table` за стилизация и използване на `br` за добавяне на отстояния. Вместо `table` използвайте `flex` или `grid` и вместо тагът `br` използвайте CSS пропъртита като margin и padding

**Comment by adikrasimirowa** [comment]
https://codepen.io/adikrasimirowa/pen/PoWWzBM нещо такова ли трябва да е ? Използвала съм grid layout за да направя една sample таблица

**Comment by yavorp** [comment]
Когато искате да имате таблица използвайте таблица `<table>.....</table>`. Но ако имате форми или нещо друго, което да бъде подредено и стилизирано, тогава използвайте грид. В този случай, който видях по-скоро `<table>`  изглежда по-подходящ
